import {
  filterNombre,
  formtFechaCorta,
  fechaFrontend,
  fechaImagenologia,
  fechaLaboratorio,
  fechaActual,
  fechaPerfil,
  orderId,
  orderDate,
  removeDuplicado,
  cadenaUpercase,
  tabActive,
  compartir,
  totalDosisTratamiento,
  fechaDiaAdd,
  imgPerfil,
  calcularEdad,
} from "./helpers";
import {
  tablaFrecuencia,
  meses,
  grupoSanguineos,
  grupodiscapacidad,
  obtenerEstadoVerificacion,
} from "./tablasHash";
import {
  NOTAB,
  INITIALPERFIL,
  INITIALCREARPERFIL,
  INITIALIMAGENOLOGIA,
  INITIALLABORATORIO,
  INITIALCONSULTA,
  FORMTRATAMIENTOS,
  FORMNIVELES,
  CONFIGNOTIFICACION,
} from "./const";
import { valEnfermedad, valTratamiento } from "./validacion";
import { fetchWrapper } from "./fetchWrapper";
export {
  /*-HELPERS-----------------------*/
  filterNombre,
  formtFechaCorta,
  fechaFrontend,
  fechaActual,
  fechaImagenologia,
  fechaLaboratorio,
  fechaPerfil,
  orderId,
  orderDate,
  removeDuplicado,
  cadenaUpercase,
  tabActive,
  compartir,
  totalDosisTratamiento,
  fechaDiaAdd,
  imgPerfil,
  calcularEdad,
  /*-TABLA-HASH------------------*/
  meses,
  tablaFrecuencia,
  grupoSanguineos,
  grupodiscapacidad,
  obtenerEstadoVerificacion,
  /*-CONSTANTES-----------------*/
  INITIALPERFIL,
  INITIALCREARPERFIL,
  NOTAB,
  FORMTRATAMIENTOS,
  FORMNIVELES,
  INITIALIMAGENOLOGIA,
  INITIALLABORATORIO,
  INITIALCONSULTA,
  CONFIGNOTIFICACION,
  /*-VALIDACIONES---------------*/
  valEnfermedad,
  valTratamiento,
  /*-BACK---------------*/
  fetchWrapper,
};
