import {
  servicesWh,
  getPost,
  /*-PERFILES----------*/
  getPerfil,
  getPerfiles,
  getPerfilEdicion,
  getFichaCompleta,
  /*-USUARIOS----------*/
  registroUsuario,
  authentication,
  /*-PACIENTES---------*/
  serviciosPaciente,
  /*-AFILIADO----------*/
  serviciosAfiliados,
  getComboAfiliados,
  getComboAfiliadosId,
  getComboAfiliadosRecientes,
  /*-CONSULTAS--------*/
  getConsultas,
  getConsultaDetalle,
  serviciosConsultas,
  getConsultasUltimoRg,
  /*-ALERGIAS----------*/
  getAlergiasPaciente,
  getGrupoAlergias,
  getAlergias,
  getCentrosProduccion,
  /*-ENFERMEDADES---*/
  getEnfermedadPaciente,
  getEnfermedad,
  /*-LABORATORIO-----*/
  getLaboratorios,
  getLaboratorioUlt,
  getLaboratoriosUltimoRg,
  /*-IMAGENOLOGIA---*/
  getImagenologias,
  getImagenologiaUlt,
  serviciosImagenologia,
  getImagenologiaUltimoRg,
  /*-TRATAMIENTOS----*/
  getMedicamentos,
  getTratamientosPacientes,
  getTipoDiagnosticosPacientes,
  /*-DISCAPACIDAD----*/
  getDicapacidadPaciente,
  /*-URL-----------------*/
  URLPERFIL,
  /*-MIS-MEDICAMENTOS-*/
  getMisMedicamentos,
  getDetailMedicamento,
  /*-MIS-MEDICOS---------*/
  getMisMedicos,
} from "./servicios";
export {
  servicesWh,
  getPost,
  /*-PERFILES----------*/
  getPerfil,
  getPerfiles,
  getPerfilEdicion,
  getFichaCompleta,
  /*-USUARIOS----------*/
  registroUsuario,
  authentication,
  /*-PACIENTES---------*/
  serviciosPaciente,
  /*-AFILIADO----------*/
  serviciosAfiliados,
  getComboAfiliados,
  getComboAfiliadosId,
  getComboAfiliadosRecientes,
  getCentrosProduccion,
  /*-CONSULTAS--------*/
  getConsultaDetalle,
  getConsultas,
  serviciosConsultas,
  getConsultasUltimoRg,
  /*-ALERGIAS----------*/
  getAlergiasPaciente,
  getGrupoAlergias,
  getAlergias,
  /*-ENFERMEDADES---*/
  getEnfermedadPaciente,
  getEnfermedad,
  /*-LABORATORIO-----*/
  getLaboratorios,
  getLaboratorioUlt,
  getLaboratoriosUltimoRg,
  /*-IMAGENOLOGIA---*/
  getImagenologias,
  getImagenologiaUlt,
  serviciosImagenologia,
  getImagenologiaUltimoRg,
  /*-TRATAMIENTOS----*/
  getMedicamentos,
  getTratamientosPacientes,
  getTipoDiagnosticosPacientes,
  /*-DISCAPACIDAD----*/
  getDicapacidadPaciente,
  /*-URL-----------------*/
  URLPERFIL,
  /*-MIS-MEDICAMENTOS-*/
  getMisMedicamentos,
  getDetailMedicamento,
  /*-MIS-MEDICOS---------*/
  getMisMedicos,
};
